### ISSUE TITLE
Implement classification_report on the test images

### ISSUE THREAD

**Issue by aarpit1010** [aarpit1010/Real-Time-Face-Mask-Detector#10]
Implement a code snippet to create a nicely formatted classification report by making predictions on all images in the test set.

More than one person can work on this issue at a time.
But, only the 1st correct and good PR will be accepted.
So, claim before starting work on the issue.

P.S. : please do follow the guidelines carefully before committing your code.

**Comment by Tanish-16** [comment]
I want to work on this issue.

**Comment by aarpit1010** [comment]
@Tanish-16 sure..go ahead, if you have any problem ping me..
