### ISSUE TITLE
[BUG] Rectangle frame is NOT displaying while detecting faces using OpenCV

### ISSUE THREAD

**Issue by aarpit1010** [aarpit1010/Real-Time-Face-Mask-Detector#5]
In the file `detection.ipynb` , there is a bug due to which while running it, the rectangular frames are not showing up while detecting face and masks.
Make a similar file in your folder having the correct code and do add a screenshot or a GIF to show whether the rectangular frame is showing up or not while detection.

Also, try to show the accuracy too besides MASK/NO MASK...

Only the first correct and good PR will be accepted.
So, claim before starting work on the issue.

**Comment by JLodha** [comment]
I want to work on this.

**Comment by aarpit1010** [comment]
@JLodha 
Sure, go ahead..
Feel free to ask if you get stuck at any point..

**Comment by Tanish-16** [comment]
I want to work on this too.

**Comment by aarpit1010** [comment]
@Tanish-16 
Sure, go ahead..
I am not assigning anyone, but only the 1st correct PR will be merged.

**Comment by aarpit1010** [comment]
@Tanish-16 @JLodha 
Updates??

**Comment by Parasagrawal** [comment]
i want to waor on this

**Comment by Parasagrawal** [comment]
i want to work on thiis

**Comment by aarpit1010** [comment]
@Parasagrawal 
A PR is already in review for this issue...
It might get merged latest by tomorrow.
If it doesn't get merged then you might submit your PR...nevertheless if you want you can work on it, I'll select the better PR amongst the two...

Also give a try to issue #6 too, you'll find many resources related to it on the internet for reference..
in the meantime I'll post some more issues..
: ) 

EDIT: I have updated the issue combining it with a previous issue for displaying accuracy along with rectangle frame...
