### ISSUE TITLE
Display Accuracy

### ISSUE THREAD

**Issue by aarpit1010** [aarpit1010/Real-Time-Face-Mask-Detector#8]
Display the accuracy of the model while detecting the face and/or mask.
You may or may not include a rectangular frame for this issue.

Only the 1st correct and good PR will be accepted.
So, claim before starting work on the issue.

**Comment by Shreesh90** [comment]
Can I?

**Comment by aarpit1010** [comment]
Sure @Shreesh90 , go for it.
